### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by mbkumar** [alejandrojuria/tightbinder#8]
Tests are missing. For code quality control, please consider adding unit tests. Python unit testing framework should be enough for your case.

**Comment by alejandrojuria** [comment]
Following your comment, I have added several tests to verify the integrity of the code. Instead of adding unit tests, I opted for functional tests that verify specific workflows within the library, specifically testing the different steps present in each type of calculation. These tests cover all the example scripts present in the repository. They can be run with pytest; I have also added a README within the `tests` folder with some brief instructions on how to run them.

**Comment by mbkumar** [comment]
In your tests, the file paths are hard-coded to the root folder. As you wrote in docs, one has to run them from root folder only. This is preventing me to run the tests from the tests folder. This is a bad design. You should instead use the relative path from the location where the script is located.
